"use client";

import { useEffect, useState } from "react";
import { CheckCircle2, Eye, ClipboardCheck, Loader2 } from "lucide-react";

type Activity = { id: string; title: string; date?: string; applicationEnabled: boolean; registrationEnabled: boolean; confirmationEnabled: boolean; hasEvaluation: boolean };

function Switch({ enabled, disabled, onClick }: { enabled: boolean; disabled?: boolean; onClick: () => void }) {
  return <button type="button" disabled={disabled} onClick={onClick} className={`relative h-7 w-12 rounded-full transition ${enabled ? "bg-[#1565C0]" : "bg-slate-300"} disabled:cursor-not-allowed disabled:opacity-50`} aria-pressed={enabled}><span className={`absolute top-1 h-5 w-5 rounded-full bg-white shadow transition ${enabled ? "left-6" : "left-1"}`} /></button>;
}

export default function ActivityWorkflowPanel() {
  const [activities,setActivities]=useState<Activity[]>([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState<string|null>(null);
  const load=async()=>{setLoading(true);try{const [a,w]=await Promise.all([fetch("/api/activities",{cache:"no-store"}),fetch("/api/activities/workflow",{cache:"no-store"})]);const ad=await a.json(),wd=await w.json();const map=new Map((Array.isArray(wd)?wd:[]).map((x:any)=>[x.activityId,x]));setActivities((Array.isArray(ad)?ad:[]).map((x:any)=>({...x,...map.get(x.id)})).filter((x:any)=>x.status==="active"));}finally{setLoading(false)}};
  useEffect(()=>{void load()},[]);
  const toggle=async(a:Activity,field:keyof Pick<Activity,"applicationEnabled"|"registrationEnabled"|"confirmationEnabled">)=>{setBusy(`${a.id}:${field}`);try{const r=await fetch("/api/activities/workflow",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({activityId:a.id,field,value:!a[field]})});const d=await r.json();if(!r.ok)throw new Error(d?.error||d?.message||"อัปเดตไม่สำเร็จ");setActivities(prev=>prev.map(x=>x.id===a.id?{...x,...d}:x));}catch(e){alert(e instanceof Error?e.message:"เกิดข้อผิดพลาด")}finally{setBusy(null)}};
  return <section className="mb-6 rounded-2xl border border-blue-100 bg-white/95 p-5 shadow-[0_14px_34px_rgba(15,23,42,0.07)]"><div className="flex items-start justify-between gap-4"><div><h2 className="text-lg font-semibold text-slate-950">ลำดับการเปิดใช้งานกิจกรรม</h2><p className="mt-1 text-sm text-slate-500">เปิดตามลำดับ: มองเห็นการสมัคร → ลงทะเบียน → ยืนยันการเข้าร่วม</p></div><div className="hidden items-center gap-2 text-xs text-slate-500 sm:flex"><Eye className="h-4 w-4"/>ควบคุมการมองเห็นและสิทธิ์ของนิสิต</div></div>{loading?<div className="flex justify-center py-8"><Loader2 className="h-6 w-6 animate-spin text-[#1565C0]"/></div>:activities.length===0?<p className="py-8 text-center text-sm text-slate-400">ไม่มีกิจกรรมที่กำลังดำเนินการ</p>:<div className="mt-5 space-y-3">{activities.map(a=><div key={a.id} className="rounded-xl border border-blue-50 bg-slate-50/60 p-4"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0"><p className="font-semibold text-slate-900">{a.title}</p><p className="mt-1 text-xs text-slate-500">ขั้นตอนจะเปิดทีละระดับ เพื่อไม่ให้นิสิตข้ามขั้น</p></div><div className="grid gap-3 sm:grid-cols-3"><div className="flex items-center gap-3 rounded-lg bg-white px-3 py-2"><Eye className="h-4 w-4 text-[#1565C0]"/><span className="w-28 text-xs font-medium">มองเห็นการสมัคร</span><Switch enabled={a.applicationEnabled} disabled={busy===`${a.id}:applicationEnabled`} onClick={()=>toggle(a,"applicationEnabled")}/></div><div className="flex items-center gap-3 rounded-lg bg-white px-3 py-2"><ClipboardCheck className="h-4 w-4 text-[#1565C0]"/><span className="w-28 text-xs font-medium">เปิดการลงทะเบียน</span><Switch enabled={a.registrationEnabled} disabled={!a.applicationEnabled||busy===`${a.id}:registrationEnabled`} onClick={()=>toggle(a,"registrationEnabled")}/></div><div className="flex items-center gap-3 rounded-lg bg-white px-3 py-2"><CheckCircle2 className="h-4 w-4 text-[#1565C0]"/><span className="w-28 text-xs font-medium">เปิดยืนยันเข้าร่วม</span><Switch enabled={a.confirmationEnabled} disabled={!a.registrationEnabled||!a.hasEvaluation||busy===`${a.id}:confirmationEnabled`} onClick={()=>toggle(a,"confirmationEnabled")}/></div></div></div></div>)}</div>}</section>;
}
